### ISSUE TITLE
Moving these issues to Mozilla-Learning repo

### ISSUE THREAD

**Issue by ldecoursy** [Saallen/Mentor-dev-doc-hub#7]
Hi @Saallen Can you let me know if these issues are still active? If so will want to move them to the  https://github.com/MozillaFoundation/Mozilla-Learning repo - I can help, just let me know. 

Thanks!

**Comment by Saallen** [comment]
Hi @ldecoursy Lainie,
These issues contain background docs for mentor learning networks- when we first talked about clubs.
I believe that most of the info has been copied to wiki pages or the information within them has been updated and re-evaluated. They are prob not very relevant anylonger. I will close them. Thanks
